name: satkit
channels:
  - conda-forge
dependencies:
  - orekit
  - pint
  - numpy
  - scipy
  - portion
  - matplotlib
# packages needed for document generation
#  - python=3.11
  - pip
  - pip:
      - ipykernel
      - nbsphinx
      - myst_parser
      - sphinx_autodoc_typehints
      - sphinx_copybutton
      - sphinx-notfound-page
      - sphinx-hoverxref