name: satkit
channels:
  - conda-forge
dependencies:
  - orekit
  - pint
  - numpy
  - scipy
  - matplotlib
  # dev dependencies
  - pytest
  - pytest-cov
  - pytest-xdist
  - black
  - isort
  - flake8
  - tox
  - tox-conda