# Python CircleCI 2.1 configuration file
version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:

  tests:

    docker:
      - image: continuumio/miniconda3

    parallelism: 4

    steps:
      # Get repo from GitHub
      - checkout
      - run:
          name: Install tox
          command: pip install tox
#      # Create venv and install dependencies - not needed as the docker image is miniconda
#      - run:
#          name: install dependencies
#          command: conda env create -f environment.yml
      - run:
          name: Run tests
          command: | 
            set -e
            TEST_FILES=$(circleci tests glob "satkit/**/test_*.py" | circleci tests split --split-by=timings)
            tox -e py310 -- $TEST_FILES
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
#      Coverage stuff below
      - run:
          name: Run coverage
          command: tox -e coverage
      - run:
          name: Prepare upload
          command: conda install -y curl
#      - run:
#          name: Prepare validation
#          command: apt-get install gpgv gpg
      - codecov/upload:
          validate: false


  codestyle:

    docker:
      - image: continuumio/miniconda3

    steps:
      # Get repo from GitHub
      - checkout
      # Create venv and install dependencies
      - run:
          name: Install Python dependencies
          command: pip install tox
      - run:
          name: Make sure style checks pass
          command: tox -e codestyle


workflows:
  tests_and_codestyle:
    jobs:
      - codestyle
      - tests

