# Python CircleCI 2.1 configuration file
version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:

  tests:

    docker:
      - image: continuumio/miniconda3

#    parallelism: 4

    steps:
      # Get repo from GitHub
      - checkout
      - run:
          name: Install tox
          command: pip install tox
#      # Create venv and install dependencies - not needed as the docker image is miniconda
#      - run:
#          name: install dependencies
#          command: conda env create -f environment.yml
      - run:
          name: Run tests
          command: tox -e py310
#      The rest is for codecov upload
      - run:
          name: Run coverage
          command: tox -e coverage
      - run:
          name: Install curl
          command: conda install -y curl
      - run:
          name: Install gpg
          command: pip install gpg
      - codecov/upload

  codecov:

    docker:
      - image: cimg/python3.10

    steps:
      # Get repo from GitHub
      - checkout
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Run coverage
          command: tox -e coverage
#      - run:
#          name: Install curl
#          command: conda install -y curl
#      - run:
#          name: Install gpg
#          command: pip install gpg
      - codecov/upload



  codestyle:

    docker:
      - image: continuumio/miniconda3

    steps:
      # Get repo from GitHub
      - checkout
      # Create venv and install dependencies
      - run:
          name: Install Python dependencies
          command: pip install tox
      - run:
          name: Make sure style checks pass
          command: tox -e codestyle

workflows:
  tests_and_codestyle:
    jobs:
      - codestyle
      - tests

