# Python CircleCI 2.1 configuration file
version: 2.1

orbs:
  python: circleci/python@2.1

jobs:
#  build_and_test: # this can be any name you choose
#    executor: python/default # use the default executor defined within the orb
#    steps:
#      - checkout # checkout source code
#      - python/install-packages:
#          pkg-manager: pip
#      - run:
#          name: Run tests
#          command: python -m pytest
#      - persist_to_workspace:
#          root: ~/project
#          paths:
#            - .

  codestyle:
#    executor: python/default # use the default executor defined within the orb
    steps:
      # Get repo from GitHub
      - checkout
      # Create venv and install dependencies
      - run:
          name: install dependencies
          command: conda env create -f environment.yml
      - run:
          name: Make sure style checks pass
          command: tox -e codestyle

workflows:
  tests_and_codestyle:
    jobs:
      - codestyle
      - tests
