# Python CircleCI 2.1 configuration file
version: 2.1

jobs:

  tests:
    docker:
      - image: cimg/python:3.10
    parallelism: 4

    steps:
      - checkout
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Run tests
          command: tox -e py310-test
      - store_test_results:
          path: test-results
      - store_artifacts:
            path: test-results
            destination: tr1


  codestyle:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
#      - run:
#          name: Install apt packages
#          command: |
#            sudo apt update
#            sudo apt install -y graphviz
      - run:
          name: Install Python dependencies
          command: pip install tox --user
      - run:
          name: Make sure style checks pass
          command: tox -e codestyle
#      - run:
#          name: Build Docs
#          command: tox -e build_docs -- -j=4
#      - store_artifacts:
#          path: docs/_build/html

workflows:
  tests_and_codestyle:
    jobs:
      - codestyle
      - tests
